name: Push_validation
on: 
    push:
    schedule:
        - cron:  '0 * * * *'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Github Action'
              uses: actions/checkout@v3

            - name: Execute script
              uses: echo "Executing workflow"

            - name: Set up .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Build app
              uses: dotnet build    